
connect_four: system execution failed.
Following is the set of recorded exceptions:

******************************** Thread exception *****************************
In thread           Root thread            0x0 (thread id)
*******************************************************************************
-------------------------------------------------------------------------------
Class / Object      Routine                Nature of exception           Effect
-------------------------------------------------------------------------------
ARRAYED_LIST        at @1                  valid_key:                   
<000000000415FD18>                         Precondition violated.        Fail
-------------------------------------------------------------------------------
APPLICATION         add_new_point @4                                    
<000000000415F5A8>                         Routine failure.              Fail
-------------------------------------------------------------------------------
APPLICATION         make @7                                             
<000000000415F5A8>                         Routine failure.              Fail
-------------------------------------------------------------------------------
APPLICATION         root's creation                                     
<000000000415F5A8>                         Routine failure.              Exit
-------------------------------------------------------------------------------
